export const Langs = [
    { label: 'English (US)', value: 'en-US' },
    { label: 'English (UK)', value: 'en-GB' },
    { label: 'Português (Brasil)', value: 'pt-BR' },
    { label: 'Português (Portugal)', value: 'pt-PT' },
    { label: '简体中文', value: 'zh-HANS' },
    { label: '繁體中文', value: 'zh-HANT' },
    { label: 'العربية', value: 'ar' },
    { label: 'Български', value: 'bg' },
    { label: 'Čeština', value: 'cs' },
    { label: 'Dansk', value: 'da' },
    { label: 'Deutsch', value: 'de' },
    { label: 'Ελληνικά', value: 'el' },
    { label: 'Español', value: 'es' },
    { label: 'Eesti', value: 'et' },
    { label: 'Suomi', value: 'fi' },
    { label: 'Français', value: 'fr' },
    { label: 'עברית', value: 'he' },
    { label: 'Magyar', value: 'hu' },
    { label: 'Bahasa Indonesia', value: 'id' },
    { label: 'Italiano', value: 'it' },
    { label: '日本語', value: 'ja' },
    { label: '한국어', value: 'ko' },
    { label: 'Lietuvių', value: 'lt' },
    { label: 'Latviešu', value: 'lv' },
    { label: 'Norsk (Bokmål)', value: 'nb' },
    { label: 'Nederlands', value: 'nl' },
    { label: 'Polski', value: 'pl' },
    { label: 'Română', value: 'ro' },
    { label: 'Русский', value: 'ru' },
    { label: 'Slovenčina', value: 'sk' },
    { label: 'Slovenščina', value: 'sl' },
    { label: 'Svenska', value: 'sv' },
    { label: 'ไทย', value: 'th' },
    { label: 'Türkçe', value: 'tr' },
    { label: 'Українська', value: 'uk' },
    { label: 'Tiếng Việt', value: 'vi' },
    { label: '中文', value: 'zh' },
];